### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by Aidenwjt** [Ty-Irving/flight-api#1]
There is nothing in here, what kind of API is this, just a readme?

**Comment by NoahPinel** [comment]
Almost two days and this is still open? wow! just goes to show the level of care the author is giving to this project... 
I recommend privatizing this empty repo.
cheers,
Npines

**Comment by NoahPinel** [comment]
> There is nothing in here, what kind of API is this, just a readme?

TRUE!!!!!

**Comment by Ty-Irving** [comment]
This will be worked on eventually... CLOSED!
